// Begin AutoGenerated Includes - DO NOT EDIT BELOW
#include <GyroPalmEngine.h>
#include <GyroPalmLVGL.h>
// End AutoGenerated Includes - DO NOT EDIT ABOVE
#include <GyroPalmESPNOW.h>

GyroPalmESPNOW gpwireless(ESPNOWrole::SERVER);
String clientAddress;

// A struct to organize data to send
// CANNOT BE > 256 BYTES
typedef struct struct_message {
  char wearableID[30];
  char action[30];
  int x;
  int y;
} struct_message;

// Begin AutoGenerated Globals - DO NOT EDIT BELOW
GyroPalm *device;
GyroPalmEngine gplm("gp123456");    //declares a GyroPalm Engine object with wearableID

AXP20X_Class *power;
lv_task_t *barTask;
void lv_update_task(struct _lv_task_t *);

lv_task_t* driveTask;
void lv_drive_task(struct _lv_task_t *);

enum Screen { SCR_HOME };  //Screen indexes
lv_obj_t *screen[1];    //screen pointers
GyroPalmLVGL form[1];   //screen helper methods
Screen curScreen = SCR_HOME;    //default screen
// End AutoGenerated Globals - DO NOT EDIT ABOVE

int targetDevice = 4;   // 0 is AMR, 1 is omni, 2 is vortex, 3 is DSLR, 4 is maze
int ir_pin = 13;

bool isDriving = false;
bool flipMode = false;

lv_obj_t *btnUndock;
lv_obj_t *btnFlip;
lv_obj_t *btnUturn;
lv_obj_t *lblStatus;

lv_obj_t *btnMaze;
lv_obj_t *btnOmni;
lv_obj_t *btnVortex;
lv_obj_t *btnDSLR;
lv_obj_t *btnAMR;

lv_obj_t *msgboxRead;

void showMsg(String msg) {
    msgboxRead = form[curScreen].createMsgBox((char *)msg.c_str(), PROMPT_OK, msgbox_handler, true);
}

void pulse_on( unsigned long duration ) {
    unsigned long stop = micros() + duration;
    while( micros() < stop ) {
        digitalWrite(ir_pin, HIGH );
        delayMicroseconds( 13 );
        digitalWrite(ir_pin, LOW );
        delayMicroseconds( 13 );
    }
}
void pulse_off( unsigned long duration ) {
    unsigned long stop = micros() + duration;
    while( micros() < stop );
}
void nikonCapture()
{
    for (int i=0; i < 2; i++) {
        pulse_on(2000);
        pulse_off(27850);
        pulse_on(390);
        pulse_off(1580);
        pulse_on(410);
        pulse_off(3580);
        pulse_on(400);
        pulse_off(63200);
    }
    lv_disp_trig_activity(NULL);    //reset inactivity counter
}

static void msgbox_handler(lv_obj_t *obj, String btnText)
{
    if (obj == msgboxRead) {
        Serial.println("Response from MsgBox A");
        msgboxRead = NULL;
    }
    Serial.print("User response: ");
    Serial.println(btnText);
}

bool sendDockCommand(bool undock)
{
    lv_disp_trig_activity(NULL);    //reset inactivity counter
    struct_message myData;

    if (undock) {
        strcpy(myData.wearableID, gplm.myLicense.wearableID);
        if (targetDevice == 0) {
            strcpy(myData.action, "srundock");
        } else if (targetDevice == 1) {
            strcpy(myData.action, "undock");
        } else if (targetDevice == 2) {
            strcpy(myData.action, "vundock");
        }
        else {

        }
        
        myData.x = 0;
        myData.y = 0;
    } else {
        strcpy(myData.wearableID, gplm.myLicense.wearableID);
        if (targetDevice == 0) {
            strcpy(myData.action, "srdock");
        } else if (targetDevice == 1) {
            strcpy(myData.action, "dock");
        } else if (targetDevice == 2) {
            strcpy(myData.action, "vdock");
        } else {

        }
        myData.x = 0;
        myData.y = 0;
    }
    return(gpwireless.sendMessage((uint8_t *)&myData, sizeof(myData), clientAddress));
}

bool sendDriveCommand()
{
    lv_disp_trig_activity(NULL);    //reset inactivity counter
    // 0 is AMR, 1 is omni, 2 is vortex, 3 is DSLR, 4 is maze
    struct_message myData;
    strcpy(myData.wearableID, gplm.myLicense.wearableID);
        if (targetDevice == 0) {
            strcpy(myData.action, "srdrive");
        } else if (targetDevice == 1) {
            strcpy(myData.action, "drive");
        } else if (targetDevice == 2) {
            strcpy(myData.action, "vdrive");
        } else if (targetDevice == 4) {
            strcpy(myData.action, "mzdrive");
        } else {

        }
    myData.x = gplm.ax;
    myData.y = gplm.ay;
    
    if (flipMode) {
        myData.x = gplm.ax;
        myData.y = gplm.ay * -1;
    }
    
    return(gpwireless.sendMessage((uint8_t *)&myData, sizeof(myData), clientAddress));
}

bool sendUturnCommand()
{
    lv_disp_trig_activity(NULL);    //reset inactivity counter
    struct_message myData;
    strcpy(myData.wearableID, gplm.myLicense.wearableID);
        if (targetDevice == 0) {
            strcpy(myData.action, "sruturn");
        } else if (targetDevice == 1) {
            strcpy(myData.action, "uturn");
        } else if (targetDevice == 2) {
            strcpy(myData.action, "vuturn");
        } else {

        }
    myData.x = 0;
    myData.y = 0;
    
    return(gpwireless.sendMessage((uint8_t *)&myData, sizeof(myData), clientAddress));
}

bool sendStateCommand(bool isStart)
{
    struct_message myData;

    // 0 is AMR, 1 is omni, 2 is vortex, 3 is DSLR, 4 is maze

    if (isStart) {  //put robot in safe mode
        strcpy(myData.wearableID, gplm.myLicense.wearableID);
        if (targetDevice == 0) {
            strcpy(myData.action, "srstart");
        } else if (targetDevice == 1) {
            strcpy(myData.action, "start");
        } else if (targetDevice == 2) {
            strcpy(myData.action, "vstart");
        }  else if (targetDevice == 4) {
            strcpy(myData.action, "mzstart");
        } else {

        }
        myData.x = 0;
        myData.y = 0;
    } else {    //tell robot to stop responding to commands
        strcpy(myData.wearableID, gplm.myLicense.wearableID);
        if (targetDevice == 0) {
            strcpy(myData.action, "srstop");
        } else if (targetDevice == 1) {
            strcpy(myData.action, "stop");
        } else if (targetDevice == 2) {
            strcpy(myData.action, "vstop");
        }  else if (targetDevice == 4) {
            strcpy(myData.action, "mzstop");
        } else {

        }
        myData.x = 0;
        myData.y = 0;
    }
    return(gpwireless.sendMessage((uint8_t *)&myData, sizeof(myData), clientAddress));
}

void OnSendError(uint8_t* ad)
{
  Serial.println("SENDING TO '"+gpwireless.macToStr(ad)+"' WAS NOT POSSIBLE!");
}

void OnPaired(uint8_t *ga, String ad)
{
  Serial.println("EspNowConnection : Client '"+ad+"' paired! ");
  gpwireless.endPairing();
  
  clientAddress = ad;
}

void OnConnected(uint8_t *ga, String ad)
{
  Serial.println("EspNowConnection : Client '"+ad+"' connected! ");
}

// Begin AutoGenerated Callbacks - DO NOT EDIT BELOW
void lv_update_task(struct _lv_task_t *data) {
    int battPercent = power->getBattPercentage();
    bool isCharging = power->isChargeing();
    form[curScreen].updateBar(battPercent, isCharging);
    form[curScreen].setTime(gplm.getTime());     //update Time View
/*
    // Auto-sleep on inactivity after 40 seconds
    const int sleepAfter = 40;
    if (lv_disp_get_inactive_time(NULL) > sleepAfter*1000) {
        onPwrQuickPress();
        lv_disp_trig_activity(NULL);    //reset inactivity counter
    }
*/
}

static void btn_event_handler(lv_obj_t * obj, lv_event_t event)
{
    if (event == LV_EVENT_CLICKED) {
        String btnName = lv_list_get_btn_text(obj);
    Serial.printf("Clicked: %s\n", btnName);

        switch (curScreen)
        {
            case SCR_HOME:
                if (btnName == "Undock") {
                    sendDockCommand(true);  //undock
                    showMsg("Undock sent!");
                }
                else if (btnName == "Dock") {
                    sendDockCommand(false);  //dock
                    showMsg("Dock sent!");
                }
                else if (btnName == "Flip") {
                    flipMode = !flipMode;
                    if (flipMode) {
                        showMsg("Flip Mode ON!");
                    } else {
                        showMsg("Flip Mode OFF!");
                    }
                }
                else if (btnName == "Uturn") {
                    sendUturnCommand();
                    showMsg("Uturn sent!");
                }
                else if (btnName == "AMR V2") { // 0 is AMR, 1 is omni, 2 is vortex, 3 is DSLR, 4 is maze
                    targetDevice = 0;
                    showMsg("AMR V2 selected!");
                }
                else if (btnName == "Omni") {
                    targetDevice = 1;
                    showMsg("OmniBot selected!");
                }
                else if (btnName == "Vortex") {
                    targetDevice = 2;
                    showMsg("Vortex selected!");
                }
                else if (btnName == "DSLR") {
                    targetDevice = 3;
                    showMsg("DSLR selected!");
                } 
                else if (btnName == "Maze") {
                    targetDevice = 4;
                    showMsg("Maze selected!");
                } else {
                    
                }
            break;

            default: break;
    }
  } else if (event == LV_EVENT_LONG_PRESSED) {
        String btnName = lv_list_get_btn_text(obj);
    Serial.printf("Long Pressed: %s\n", btnName);

        if (btnName == "Hold to Activate") {
            form[curScreen].removeDropdown();
            lv_task_handler();
            gplm.vibratePress();
            setDriving(true);   //send start driving intent
        }
    }
}

// End AutoGenerated Callbacks - DO NOT EDIT ABOVE

// Begin AutoGenerated Screens - DO NOT EDIT BELOW
void showApp(int page) {
    if ((Screen) page != curScreen) {
        form[curScreen].removeBar();    //remove old StatusBar before proceeding
    }

    switch (page)
    {
    case SCR_HOME:
        {
            //Draw screen UI
            curScreen = (Screen) page;
            form[curScreen].init(screen[curScreen]);  //now defining screen items
            form[curScreen].createBar(barTask, lv_update_task);
            form[curScreen].setTime(gplm.getTime());
      form[curScreen].createLabel(-35, -54, "Robot Control");    //show element
      lblStatus = form[curScreen].createLabel(-35, -25, "Status: Standy");    //show element
            btnDSLR = form[curScreen].createButton(78, -40, "DSLR", btn_event_handler, true, 59);    //show element

            btnMaze = form[curScreen].createButton(-78, 25, "Maze", btn_event_handler, true, 62);    //show element
            btnOmni = form[curScreen].createButton(0, 25, "Omni", btn_event_handler, true, 62);    //show element
            btnVortex = form[curScreen].createButton(78, 25, "Vortex", btn_event_handler, true, 62);    //show element

      btnAMR = form[curScreen].createButton(-77, 84, "AMR V2", btn_event_handler, true, 59);    //show element
      btnFlip = form[curScreen].createButton(0, 84, "Flip", btn_event_handler, true, 59);    //show element
      btnUturn = form[curScreen].createButton(77, 84, "Uturn", btn_event_handler, true, 59);    //show element

            form[curScreen].showScreen(ANIM_NONE);   //show the screen w/ no animation
        }
        break;


        default: break;
    }
    gplm.setScreen(&form[curScreen]);
    form[curScreen].setBarCallback(bar_handler);
}
// End AutoGenerated Screens - DO NOT EDIT ABOVE

void bar_handler(int barIntent)
{
    switch(barIntent)
    {
        //Prints Pressing
        case BAR_PRESSING:
            Serial.println("Pressing");
            break;

        //Prints Swipe Left and Returns User to HomePage
        case BAR_SWIPE_LEFT:
            Serial.println("Swipe Left");
            showApp(SCR_HOME);
            break;

        //Prints Swipe Right
        case BAR_SWIPE_RIGHT:
            Serial.println("Swipe right");
            break;

        //Prints Released
        case BAR_RELEASED:
            Serial.println("Released");
            break;

        //Calls when dropdown shown
        case DRAWER_SHOW:
            Serial.println("Dropdown Shown");
            showDrawer();
            break;

        //Calls when dropdown hidden
        case DRAWER_HIDE:
            Serial.println("Dropdown Hidden");
            break;
    }
} 

void showDrawer()
{
    // Add manual Activation button
    lv_obj_t * btn1Label;
    lv_obj_t * btn1 = lv_btn_create(form[curScreen].drawer, NULL);  //add button to page
    lv_obj_set_width(btn1, 180); //button width
    lv_obj_set_style_local_radius(btn1, LV_BTN_PART_MAIN, LV_STATE_DEFAULT, 8);
    lv_obj_align(btn1, NULL, LV_ALIGN_IN_TOP_MID, 0, 15);  //alignment
    btn1Label = lv_label_create(btn1, NULL);
    lv_label_set_text(btn1Label, "Hold to Activate");   //name of button
    lv_obj_set_event_cb(btn1, btn_event_handler);   //event handler

    int yStart = 5;

    //Create a long label
    if (flipMode) {
        lv_obj_t * lblLine0 = lv_label_create(form[curScreen].drawer, NULL);
        lv_label_set_long_mode(lblLine0, LV_LABEL_LONG_BREAK);            //Automatically break long lines
        lv_obj_set_width(lblLine0, 200);          //Set the label width to max value to not show hor. scroll bars
        lv_label_set_text(lblLine0, "Flip Mode ON");   //set label
        lv_obj_align(lblLine0, NULL, LV_ALIGN_CENTER, 15, yStart - 18);  //align underneath buttons
    }

    //Create a long label
    lv_obj_t * lblLine1 = lv_label_create(form[curScreen].drawer, NULL);
    lv_label_set_long_mode(lblLine1, LV_LABEL_LONG_BREAK);            //Automatically break long lines
    lv_obj_set_width(lblLine1, 200);          //Set the label width to max value to not show hor. scroll bars
    lv_label_set_text_fmt(lblLine1, "Wearable: %s", gplm.myLicense.wearableID);   //set label dynamically
    lv_obj_align(lblLine1, NULL, LV_ALIGN_CENTER, 15, yStart);  //align underneath buttons

    //Create a long label
    String projectID = "{{appID}}";
    lv_obj_t * lblLine2 = lv_label_create(form[curScreen].drawer, NULL);
    lv_label_set_long_mode(lblLine2, LV_LABEL_LONG_BREAK);            //Automatically break long lines
    lv_obj_set_width(lblLine2, 200);          //Set the label width to max value to not show hor. scroll bars
    lv_label_set_text_fmt(lblLine2, "Firmware: %s", projectID.c_str());   //set label dynamically
    lv_obj_align(lblLine2, NULL, LV_ALIGN_CENTER, 15, yStart + 18);  //align underneath buttons

    if (power->isVBUSPlug()) {
        //Create a long label
        // Get USB voltage in millivolts (mV)
        float Vbus = power->getVbusVoltage();
        lv_obj_t * lblLine3 = lv_label_create(form[curScreen].drawer, NULL);
        lv_label_set_long_mode(lblLine3, LV_LABEL_LONG_BREAK);            //Automatically break long lines
        lv_obj_set_width(lblLine3, 200);          //Set the label width to max value to not show hor. scroll bars
        lv_label_set_text_fmt(lblLine3, "Vbus: %.2f V", Vbus / 1000.0); // Format to Volts and set text directly
        lv_obj_align(lblLine3, NULL, LV_ALIGN_CENTER, 15, yStart + 36);  //align underneath buttons

        //Create a long label
        // Get USB current in milliamps (mA)
        float VbusCurrent = power->getVbusCurrent();
        lv_obj_t * lblLine4 = lv_label_create(form[curScreen].drawer, NULL);
        lv_label_set_long_mode(lblLine4, LV_LABEL_LONG_BREAK);            //Automatically break long lines
        lv_obj_set_width(lblLine4, 200);          //Set the label width to max value to not show hor. scroll bars
        lv_label_set_text_fmt(lblLine4, "Ibus: %.2f mA", VbusCurrent); // Format to Volts and set text directly
        lv_obj_align(lblLine4, NULL, LV_ALIGN_CENTER, 15, yStart + 54);  //align underneath buttons

        //Create a long label
        // Get Battery charge current in milliamps (mA)
        float chargeCurrent = power->getBattChargeCurrent();
        lv_obj_t * lblLine5 = lv_label_create(form[curScreen].drawer, NULL);
        lv_label_set_long_mode(lblLine5, LV_LABEL_LONG_BREAK);            //Automatically break long lines
        lv_obj_set_width(lblLine5, 200);          //Set the label width to max value to not show hor. scroll bars
        lv_label_set_text_fmt(lblLine5, "Ibatt: %.2f mA", chargeCurrent); // Format to Volts and set text directly
        lv_obj_align(lblLine5, NULL, LV_ALIGN_CENTER, 15, yStart + 72);  //align underneath buttons
    } else {
        //Create a long label
        // Get Battery current consumption in milliamps (mA)
        float dischargeCurrent = device->power->getBattDischargeCurrent();
        lv_obj_t * lblLine3 = lv_label_create(form[curScreen].drawer, NULL);
        lv_label_set_long_mode(lblLine3, LV_LABEL_LONG_BREAK);            //Automatically break long lines
        lv_obj_set_width(lblLine3, 200);          //Set the label width to max value to not show hor. scroll bars
        lv_label_set_text_fmt(lblLine3, "Idrain: %.2f mA", dischargeCurrent); // Format to Volts and set text directly
        lv_obj_align(lblLine3, NULL, LV_ALIGN_CENTER, 15, yStart + 36);  //align underneath buttons
    }
    
}

void onPwrQuickPress() {
    gplm.toggleSleep();
    if (gplm.isSleep) {
        // Turn off unused interrupts while sleep
        gplm.sensor->enableStepCountInterrupt(false);
        gplm.sensor->enableWakeupInterrupt(false);
        gplm.sensor->enableActivityInterrupt(false);
    } else {
        // Restore interrupts
        delay(5);
        gplm.sensor->enableStepCountInterrupt(true);
        gplm.sensor->enableWakeupInterrupt(true);
        gplm.sensor->enableActivityInterrupt(true);

    }
}

void onGlance(bool isGlanced)
{
    if (gplm.isActive == false) {   //only takes effect if wearable not active
        if (isGlanced) {
            form[curScreen].showIcon(BAR_GLANCE);
        } else {
            form[curScreen].hideIcon(BAR_GLANCE);
        }
    }
}

void onActivation(bool isActive)
{
    if (isActive) {
        Serial.println("Activated!");
        form[curScreen].setIconColor(BAR_GLANCE, LV_COLOR_CYAN);
        // your code here, once wearable is activated
        if (targetDevice == 3) {
            gplm.setActive(false);
            delay(1500);
            nikonCapture();
            showMsg("Camera triggered!");
        }
    } else {
        Serial.println("Deactivated!");
        form[curScreen].setIconColor(BAR_GLANCE, LV_COLOR_WHITE);
        form[curScreen].hideIcon(BAR_GLANCE);
        // your code here, once wearable is deactivated
    }
}

void setDriving(bool stat)
{
    isDriving = stat;
    sendStateCommand(stat);
    if (stat) {
        lv_label_set_text(lblStatus, "Status: Drive");
    } else {
        lv_label_set_text(lblStatus, "Status: Standby");
    }
}

void onDeviceTilt(int direction)
{
    if (direction == LH_UPSIDEDOWN) {
        gplm.setActive(false);  //disable control since user performed hand-drop gesture
        setDriving(false);   //send stop driving intent
    }

    //only for activated commands --------------

    if (gplm.isActive != true) { // Ignore event if gesture performed without activation
        return;
    }

    switch(direction)
    {
        case LH_LEFT:
            gplm.setActive(false);  // Action completed, redeem activation
            setDriving(true);   //send start driving intent
        break;

        case LH_RIGHT:
            gplm.setActive(false);  // Action completed, redeem activation
            //lv_event_send(btnFlip, LV_EVENT_CLICKED, NULL); //dock requested
        break;

        default: 
            gplm.setActive(false);  // Action completed, redeem activation
        break;
    }
}

//Insert this before:
void lv_drive_task(struct _lv_task_t *data) {
    
    if (isDriving) {
        sendDriveCommand();
    }
}

typedef struct struct_vel_message {
  char action[30];
  float lTarget;
  float rTarget;
  float lActual;
  float rActual;
  
} struct_vel_message;

void handlePowerWake() {
    power->readIRQ();
    if (gplm.isSleep && power->isPEKShortPressIRQ()) {
        Serial.println("GyroPalm wake");
        onPwrQuickPress();

        esp_now_deinit();
        WiFi.disconnect();
        clientAddress = "FFFFFFFFFFFF";
        gpwireless.begin();
        gpwireless.onPaired(&OnPaired);  
        gpwireless.onSendError(&OnSendError);
        gpwireless.onConnected(&OnConnected); 
    }
}

void setup() {

    // Begin AutoGenerated Setup - DO NOT EDIT BELOW
  gplm.begin();
  delay(100);
  gplm.listenEvents(false);    //starts listening for events

    gplm.setGlanceCallback(onGlance);   // use onGlance as a helper
    gplm.setPwrQuickPressCallback(onPwrQuickPress);
    gplm.setTiltCallback(onDeviceTilt); // use onDeviceTilt as a navigation gesture
    delay(100);

    gplm.autoTimeout = true;    //tells the wearable to deactivate automatically
    gplm.deactivateTimeout = 3000;  // (optional) timeout in miliseconds (3 seconds default)
    gplm.activationGesture = ACT_DOUBLE_SNAP;   // (optional) ACT_DOUBLE_SNAP by default
    gplm.setActivationCallback(onActivation);   // register activation gesture callback

  device = gplm.wearable; //gives control to the developer to run device methods
  device->lvgl_begin();   //Initiate LVGL core
  device->bl->adjust(90);    //Lower the brightness
  power = gplm.power;   //gives control to the developer to access power methods
  power->setChargeControlCur(300);    //enable fast charging

  showApp(curScreen);
  // End AutoGenerated Setup - DO NOT EDIT ABOVE


    //clientAddress = "409151449602";
    clientAddress = "FFFFFFFFFFFF";
    gpwireless.begin();
    gpwireless.onPaired(&OnPaired);  
    gpwireless.onSendError(&OnSendError);
    gpwireless.onConnected(&OnConnected);  

    //Serial.println(WiFi.macAddress());
    //gpwireless.startPairing(30);

    Serial.println("Performing self calibration");
    gplm.doCalibration(10);
    Serial.println("Calibration complete");

    driveTask = lv_task_create(lv_drive_task, 80, LV_TASK_PRIO_LOWEST, NULL); //run task every 1 seconds

}

void loop() {
    gpwireless.loop();

    // Begin AutoGenerated Loop - DO NOT EDIT BELOW
    handlePowerWake();
  lv_task_handler();
  delay(30);
  // End AutoGenerated Loop - DO NOT EDIT ABOVE
}
